import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'TypeScript 系统教程',
  description: '从编程基础到工程实践 —— 面向有编程基础（Python/Java/C++）但未学过 JavaScript 学生的 TypeScript 教程',
  lang: 'zh-CN',
  // GitHub Pages 部署：仓库名作为 base
  base: '/typescript-tutorial/',
  lastUpdated: true,

  head: [
    ['link', { rel: 'icon', href: '/typescript-tutorial/favicon.svg' }],
  ],

  themeConfig: {
    logo: '/ts-logo.svg',
    nav: [
      { text: '首页', link: '/' },
      {
        text: '目录',
        items: [
          {
            text: '入门',
            items: [
              { text: '第一章 开篇', link: '/ch01' },
              { text: '第二章 环境搭建', link: '/ch02' },
              { text: '第三章 JS 快速补课', link: '/ch03' },
              { text: '第四章 基础类型系统', link: '/ch04' },
            ],
          },
          {
            text: '核心',
            items: [
              { text: '第五章 函数类型', link: '/ch05' },
              { text: '第六章 对象类型与接口', link: '/ch06' },
              { text: '第七章 类型收窄', link: '/ch07' },
              { text: '第八章 推导与断言', link: '/ch08' },
            ],
          },
          {
            text: '进阶',
            items: [
              { text: '第九章 泛型', link: '/ch09' },
              { text: '第十章 类', link: '/ch10' },
              { text: '第十一章 模块系统', link: '/ch11' },
              { text: '第十二章 声明文件', link: '/ch12' },
            ],
          },
          {
            text: '提高',
            items: [
              { text: '第十三章 高级类型（选读）', link: '/ch13' },
              { text: '第十四章 Zod 运行时验证', link: '/ch14' },
            ],
          },
          {
            text: '实践',
            items: [
              { text: '练习建议', link: '/exercises' },
              { text: '附录 A tsconfig 配置', link: '/appendix-a' },
              { text: '附录 B 工具类型', link: '/appendix-b' },
              { text: '附录 C 真实项目实践', link: '/appendix-c' },
            ],
          },
        ],
      },
      {
        text: '参考',
        items: [
          { text: 'TypeScript 官方文档', link: 'https://www.typescriptlang.org/docs/' },
          { text: 'TypeScript Playground', link: 'https://www.typescriptlang.org/play/' },
          { text: 'Zod 官方文档', link: 'https://zod.dev/' },
        ],
      },
    ],

    sidebar: [
      { text: "入门", collapsed: false, items: [
        { text: "第一章 开篇", collapsed: true, items: [
          { text: "1.1 JavaScript 的困局", link: "/ch01#_1-1-javascript-的困局" },
          { text: "1.2 TypeScript 的解决思路", link: "/ch01#_1-2-typescript-的解决思路" },
          { text: "1.3 类型 vs. 其他语言的对比", link: "/ch01#_1-3-类型-vs-其他语言的对比" },
          { text: "1.4 核心原则", link: "/ch01#_1-4-核心原则" },
          { text: "本章练习", link: "/ch01#本章练习" },
        ] },
        { text: "第二章 环境搭建", collapsed: true, items: [
          { text: "2.1 安装", link: "/ch02#_2-1-安装" },
          { text: "2.2 第一个程序", link: "/ch02#_2-2-第一个程序" },
          { text: "2.3 编译选项", link: "/ch02#_2-3-编译选项" },
          { text: "2.4 tsconfig.json —— 项目级配置", link: "/ch02#_2-4-tsconfig-json-——-项目级配置" },
          { text: "2.5 VSCode 编辑器支持", link: "/ch02#_2-5-vscode-编辑器支持" },
          { text: "本章练习", link: "/ch02#本章练习" },
        ] },
        { text: "第三章 JS 快速补课", collapsed: true, items: [
          { text: "前置知识：JS 特有的概念", link: "/ch03#前置知识-js-特有的概念" },
          { text: "3.1 变量声明：let 和 const", link: "/ch03#_3-1-变量声明-let-和-const" },
          { text: "3.2 基本类型", link: "/ch03#_3-2-基本类型" },
          { text: "3.3 模板字符串（Template Literals）", link: "/ch03#_3-3-模板字符串-template-literals" },
          { text: "3.4 箭头函数", link: "/ch03#_3-4-箭头函数" },
          { text: "3.5 严格相等 ===", link: "/ch03#_3-5-严格相等" },
          { text: "3.6 对象字面量", link: "/ch03#_3-6-对象字面量" },
          { text: "3.7 数组", link: "/ch03#_3-7-数组" },
          { text: "3.8 解构赋值", link: "/ch03#_3-8-解构赋值" },
          { text: "本章练习", link: "/ch03#本章练习" },
        ] },
        { text: "第四章 基础类型系统", collapsed: true, items: [
          { text: "4.1 类型注解语法", link: "/ch04#_4-1-类型注解语法" },
          { text: "4.2 原始类型", link: "/ch04#_4-2-原始类型" },
          { text: "4.3 object 类型", link: "/ch04#_4-3-object-类型" },
          { text: "4.4 数组", link: "/ch04#_4-4-数组" },
          { text: "4.5 联合类型（Union Types）", link: "/ch04#_4-5-联合类型-union-types" },
          { text: "4.6 类型别名（Type Aliases）", link: "/ch04#_4-6-类型别名-type-aliases" },
          { text: "4.7 any —— 逃生舱", link: "/ch04#_4-7-any-——-逃生舱" },
          { text: "4.8 unknown —— 安全的 any", link: "/ch04#_4-8-unknown-——-安全的-any" },
          { text: "4.9 void、never 和 undefined", link: "/ch04#_4-9-void、never-和-undefined" },
          { text: "4.10 字面量类型（Literal Types）", link: "/ch04#_4-10-字面量类型-literal-types" },
          { text: "4.11 as const —— 断言字面量类型", link: "/ch04#_4-11-as-const-——-断言字面量类型" },
          { text: "4.12 enum —— 枚举类型", link: "/ch04#_4-12-enum-——-枚举类型" },
          { text: "本章练习", link: "/ch04#本章练习" },
        ] },
      ] },
      { text: "核心", collapsed: false, items: [
        { text: "第五章 函数类型", collapsed: true, items: [
          { text: "5.1 参数类型和返回值类型", link: "/ch05#_5-1-参数类型和返回值类型" },
          { text: "5.2 可选参数与默认参数", link: "/ch05#_5-2-可选参数与默认参数" },
          { text: "5.3 剩余参数", link: "/ch05#_5-3-剩余参数" },
          { text: "5.4 函数类型表达式", link: "/ch05#_5-4-函数类型表达式" },
          { text: "5.5 回调函数的参数类型", link: "/ch05#_5-5-回调函数的参数类型" },
          { text: "5.6 函数重载", link: "/ch05#_5-6-函数重载" },
          { text: "5.7 调用签名（Call Signatures）", link: "/ch05#_5-7-调用签名-call-signatures" },
          { text: "5.8 构造签名（Construct Signatures）", link: "/ch05#_5-8-构造签名-construct-signatures" },
          { text: "5.9 泛型函数（Generic Functions）", link: "/ch05#_5-9-泛型函数-generic-functions" },
          { text: "5.10 回调函数的参数最佳实践", link: "/ch05#_5-10-回调函数的参数最佳实践" },
          { text: "5.11 void 与 undefined 的区别", link: "/ch05#_5-11-void-与-undefined-的区别" },
          { text: "5.12 函数重载的编写指南", link: "/ch05#_5-12-函数重载的编写指南" },
          { text: "5.13 剩余参数与展开（Rest / Spread）", link: "/ch05#_5-13-剩余参数与展开-rest-spread" },
          { text: "5.14 参数解构的类型注解", link: "/ch05#_5-14-参数解构的类型注解" },
          { text: "5.15 async 函数与 Promise 类型", link: "/ch05#_5-15-async-函数与-promise-类型" },
          { text: "5.16 声明 this 的类型", link: "/ch05#_5-16-声明-this-的类型" },
          { text: "本章练习", link: "/ch05#本章练习" },
        ] },
        { text: "第六章 对象类型与接口", collapsed: true, items: [
          { text: "6.1 对象类型注解", link: "/ch06#_6-1-对象类型注解" },
          { text: "6.2 可选属性", link: "/ch06#_6-2-可选属性" },
          { text: "6.3 只读属性", link: "/ch06#_6-3-只读属性" },
          { text: "6.4 Type 别名", link: "/ch06#_6-4-type-别名" },
          { text: "6.5 Interface 声明", link: "/ch06#_6-5-interface-声明" },
          { text: "6.6 type vs interface：关键差异", link: "/ch06#_6-6-type-vs-interface-关键差异" },
          { text: "6.7 索引签名", link: "/ch06#_6-7-索引签名" },
          { text: "6.8 多余属性检查（Excess Property Checks）", link: "/ch06#_6-8-多余属性检查-excess-property-checks" },
          { text: "6.9 扩展类型（Extending Types）", link: "/ch06#_6-9-扩展类型-extending-types" },
          { text: "6.10 交叉类型（Intersection Types）", link: "/ch06#_6-10-交叉类型-intersection-types" },
          { text: "6.11 泛型对象类型", link: "/ch06#_6-11-泛型对象类型" },
          { text: "6.12 元组类型（Tuple Types）", link: "/ch06#_6-12-元组类型-tuple-types" },
          { text: "本章练习", link: "/ch06#本章练习" },
        ] },
        { text: "第七章 类型收窄", collapsed: true, items: [
          { text: "7.1 联合类型", link: "/ch07#_7-1-联合类型" },
          { text: "7.2 类型收窄（Narrowing）概述", link: "/ch07#_7-2-类型收窄-narrowing-概述" },
          { text: "7.3 可辨识联合（Discriminated Union）", link: "/ch07#_7-3-可辨识联合-discriminated-union" },
          { text: "7.4 穷尽性检查（Exhaustiveness Checking）与 never", link: "/ch07#_7-4-穷尽性检查-exhaustiveness-checking-与-never" },
          { text: "7.5 字面量类型", link: "/ch07#_7-5-字面量类型" },
          { text: "7.6 字面量推断问题", link: "/ch07#_7-6-字面量推断问题" },
          { text: "本章练习", link: "/ch07#本章练习" },
        ] },
        { text: "第八章 推导与断言", collapsed: true, items: [
          { text: "8.1 类型推导", link: "/ch08#_8-1-类型推导" },
          { text: "8.2 类型断言（Type Assertions）", link: "/ch08#_8-2-类型断言-type-assertions" },
          { text: "8.3 @ts-expect-error —— 抑制类型错误", link: "/ch08#_8-3-ts-expect-error-——-抑制类型错误" },
          { text: "8.4 非空断言（Non-null Assertion !）", link: "/ch08#_8-4-非空断言-non-null-assertion" },
          { text: "8.5 satisfies 运算符", link: "/ch08#_8-5-satisfies-运算符" },
          { text: "本章练习", link: "/ch08#本章练习" },
        ] },
      ] },
      { text: "进阶", collapsed: false, items: [
        { text: "第九章 泛型", collapsed: true, items: [
          { text: "9.1 为什么需要泛型", link: "/ch09#_9-1-为什么需要泛型" },
          { text: "9.2 泛型函数", link: "/ch09#_9-2-泛型函数" },
          { text: "9.3 多个类型参数", link: "/ch09#_9-3-多个类型参数" },
          { text: "9.4 泛型约束", link: "/ch09#_9-4-泛型约束" },
          { text: "9.5 泛型接口与泛型别名", link: "/ch09#_9-5-泛型接口与泛型别名" },
          { text: "9.6 泛型类", link: "/ch09#_9-6-泛型类" },
          { text: "9.7 泛型约束与条件类型的实用模式", link: "/ch09#_9-7-泛型约束与条件类型的实用模式" },
          { text: "本章练习", link: "/ch09#本章练习" },
        ] },
        { text: "第十章 类", collapsed: true, items: [
          { text: "10.1 基本语法", link: "/ch10#_10-1-基本语法" },
          { text: "10.2 可见性修饰符", link: "/ch10#_10-2-可见性修饰符" },
          { text: "10.3 参数属性简写", link: "/ch10#_10-3-参数属性简写" },
          { text: "10.4 readonly", link: "/ch10#_10-4-readonly" },
          { text: "10.5 存取器（Getters / Setters）", link: "/ch10#_10-5-存取器-getters-setters" },
          { text: "10.6 private vs #（硬私有）", link: "/ch10#_10-6-private-vs-硬私有" },
          { text: "10.7 继承", link: "/ch10#_10-7-继承" },
          { text: "10.8 抽象类", link: "/ch10#_10-8-抽象类" },
          { text: "10.9 implements 与 interface", link: "/ch10#_10-9-implements-与-interface" },
          { text: "10.10 静态成员", link: "/ch10#_10-10-静态成员" },
          { text: "10.11 装饰器（Decorators）简介", link: "/ch10#_10-11-装饰器-decorators-简介" },
          { text: "本章练习", link: "/ch10#本章练习" },
        ] },
        { text: "第十一章 模块系统", collapsed: true, items: [
          { text: "11.1 导出与导入", link: "/ch11#_11-1-导出与导入" },
          { text: "11.2 默认导出", link: "/ch11#_11-2-默认导出" },
          { text: "11.3 重命名导入/导出", link: "/ch11#_11-3-重命名导入-导出" },
          { text: "11.4 类型专用导入/导出", link: "/ch11#_11-4-类型专用导入-导出" },
          { text: "11.5 CommonJS 与 ES Module 的互操作", link: "/ch11#_11-5-commonjs-与-es-module-的互操作" },
          { text: "本章练习", link: "/ch11#本章练习" },
        ] },
        { text: "第十二章 声明文件", collapsed: true, items: [
          { text: "12.1 什么是声明文件（.d.ts）", link: "/ch12#_12-1-什么是声明文件-d-ts" },
          { text: "12.2 DefinitelyTyped 与 @types", link: "/ch12#_12-2-definitelytyped-与-types" },
          { text: "12.3 自己编写声明文件", link: "/ch12#_12-3-自己编写声明文件" },
          { text: "12.4 三斜线指令（Triple-Slash Directives）", link: "/ch12#_12-4-三斜线指令-triple-slash-directives" },
          { text: "本章练习", link: "/ch12#本章练习" },
        ] },
      ] },
      { text: "提高", collapsed: false, items: [
        { text: "第十三章 高级类型（选读）", collapsed: true, items: [
          { text: "13.1 索引访问类型", link: "/ch13#_13-1-索引访问类型" },
          { text: "13.2 keyof 类型操作符", link: "/ch13#_13-2-keyof-类型操作符" },
          { text: "13.3 typeof 类型操作符", link: "/ch13#_13-3-typeof-类型操作符" },
          { text: "13.4 条件类型", link: "/ch13#_13-4-条件类型" },
          { text: "13.5 映射类型", link: "/ch13#_13-5-映射类型" },
          { text: "13.6 模板字面量类型", link: "/ch13#_13-6-模板字面量类型" },
          { text: "本章练习", link: "/ch13#本章练习" },
        ] },
        { text: "第十四章 Zod 运行时验证", collapsed: true, items: [
          { text: "14.1 为什么需要 Zod", link: "/ch14#_14-1-为什么需要-zod" },
          { text: "14.2 安装与基本用法", link: "/ch14#_14-2-安装与基本用法" },
          { text: "14.3 错误处理", link: "/ch14#_14-3-错误处理" },
          { text: "14.4 从 Schema 推断 TypeScript 类型", link: "/ch14#_14-4-从-schema-推断-typescript-类型" },
          { text: "14.5 常用 Schema 类型", link: "/ch14#_14-5-常用-schema-类型" },
          { text: "14.6 字符串验证", link: "/ch14#_14-6-字符串验证" },
          { text: "14.7 数字验证", link: "/ch14#_14-7-数字验证" },
          { text: "14.8 对象、数组与枚举", link: "/ch14#_14-8-对象、数组与枚举" },
          { text: "14.9 联合类型与可辨识联合", link: "/ch14#_14-9-联合类型与可辨识联合" },
          { text: "14.10 Transform 与默认值", link: "/ch14#_14-10-transform-与默认值" },
          { text: "14.11 实战：验证 API 响应", link: "/ch14#_14-11-实战-验证-api-响应" },
          { text: "本章练习", link: "/ch14#本章练习" },
        ] },
      ] },
      { text: "练习与附录", collapsed: false, items: [
        { text: "练习建议", collapsed: true, items: [
          { text: "基础类型（第四章）", link: "/exercises#基础类型-第四章" },
          { text: "函数（第五章）", link: "/exercises#函数-第五章" },
          { text: "类型收窄（第七章）", link: "/exercises#类型收窄-第七章" },
          { text: "常见报错及解决", link: "/exercises#常见报错及解决" },
        ] },
        { text: "附录 A tsconfig 配置", collapsed: true, items: [
          { text: "前端应用项目（Vite/React/Vue）", link: "/appendix-a#前端应用项目-vite-react-vue" },
          { text: "Node.js / 库项目", link: "/appendix-a#node-js-库项目" },
          { text: "严格模式全家桶", link: "/appendix-a#严格模式全家桶" },
          { text: "TypeScript 6.0 / 7.0 主要变更（2026 年发布）", link: "/appendix-a#typescript-6-0-7-0-主要变更-2026-年发布" },
        ] },
        { text: "附录 B 工具类型", link: "/appendix-b" },
        { text: "附录 C 真实项目实践", collapsed: true, items: [
          { text: "C.1 用 Node.js 开发", link: "/appendix-c#c-1-用-node-js-开发" },
          { text: "C.2 用 React 开发", link: "/appendix-c#c-2-用-react-开发" },
          { text: "C.3 直接运行 TS（开发时）", link: "/appendix-c#c-3-直接运行-ts-开发时" },
          { text: "C.4 包发布", link: "/appendix-c#c-4-包发布" },
        ] },
      ] },
    ],

    search: {
      provider: 'local',
      options: {
        translations: {
          button: { buttonText: '搜索', buttonAriaLabel: '搜索文档' },
          modal: {
            noResultsText: '没有找到相关内容',
            resetButtonTitle: '清除搜索条件',
            footer: { selectText: '选择', navigateText: '切换', closeText: '关闭' },
          },
        },
      },
    },

    docFooter: { prev: '上一页', next: '下一页' },
    outline: { label: '本页目录', level: [2, 3] },
    darkModeSwitchLabel: '外观',
    sidebarMenuLabel: '菜单',
    returnToTopLabel: '返回顶部',
    lastUpdated: { text: '最后更新', formatOptions: { dateStyle: 'short', timeStyle: 'short' } },
    editLink: {
      pattern: 'https://github.com/TsiaohanWang/typescript-tutorial/edit/master/docs/:path',
      text: '在 GitHub 上编辑本页',
    },
    externalLinkIcon: true,
  },
})
